### ISSUE TITLE
I dont know how to use the wep or the passwordless

### ISSUE THREAD

**Issue by AdrianDST** [JamieJQuinn/IR-GTS#1]
I run the program and it gives me the dns,but when i put it on the wifi settings it doesn´t recognise it.I think it´s probably because i dont know how to use the wireless network

**Comment by JamieJQuinn** [comment]
@AdrianDST Sorry to take so long to get to you! WEP or passwordless are settings you'd set in your router. I keep a spare one handy just for this because you don't really want to be messing with your main router and potentially compromising your own wifi network.

**Comment by AdrianDST** [comment]
Np,i could figure it out,but thx for responding
